[package]
name = "advanced-features"
version = "0.1.0"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
edition = "2018"

[dependencies]
hello-macro = { path = "hello-macro" }
hello-macro-derive = { path = "hello-macro/hello-macro-derive" }
