[workspace]
members = [
	"the-book/common-programming-concepts",
	"the-book/guessing-game",
	"the-book/understanding-ownership",
	"the-book/using-structs-to-structure-related-data",
	"the-book/enums-and-pattern-matching",
	"the-book/managing-growing-projects-with-packages-crates-and-modules",
]